# Generated by Django 3.1.7 on 2021-07-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.CharField(blank=True, max_length=300)),
                ('facebook_url', models.CharField(blank=True, max_length=300)),
                ('instagram_url', models.CharField(blank=True, max_length=300)),
                ('pinterest_url', models.CharField(blank=True, max_length=300)),
                ('dribble_url', models.CharField(blank=True, max_length=300)),
                ('linkedin_url', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
